#!/usr/bin/env python3

"""

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

"""

# https://oeis.org/A046180
def hexpen(n):
    if n < 0:
        return 0
    a = 1
    b = 40755
    c = 1533776805
    for i in range(n):
        d = 37635*c - 37635*b + a
        a = b
        b = c
        c = d
    return a

def solve(v):
    r = 0
    i = 0
    while True:
        r = hexpen(i)
        if r > v:
            break
        i += 1
    return r

def main():
    print(solve(40755))

main()
