#!/bin/awk -f

# Pascal's triangle is generated by starting with a 1 on the first row. On subsequent rows, the number is determined by the sum of the two numbers directly above it to the left and right.
#
# To demonstrate, here are the first 5 rows of Pascal's triangle:
#
#     1
#    1 1
#   1 2 1
#  1 3 3 1
# 1 4 6 4 1
# The Challenge
# Given an input n (provided however is most convenient in your chosen language), generate the first n rows of Pascal's triangle. You may assume that n is an integer inclusively between 1 and 25. There must be a line break between each row and a space between each number, but aside from that, you may format it however you like.
#
# This is code-golf, so the shortest solution wins.
#
# Example I/O
# > 1
# 1
# > 9
# 1
# 1 1
# 1 2 1
# 1 3 3 1
# 1 4 6 4 1
# 1 5 10 10 5 1
# 1 6 15 20 15 6 1
# 1 7 21 35 35 21 7 1
# 1 8 28 56 70 56 28 8 1

{
	for (i = 0; i < $1; i++) {
		for (j = i; j >= 0; j--) {
			if (i)
				Y[j] += Y[j-1];
			else
				Y[j] += 1;
			printf "%d ", Y[j];
		}
		printf "\n";
	}
}
