#!/usr/bin/env python3

"""

Generate a Koch Snowflake
A Koch snowflake is a triangle that for each n, another equilateral point is added in the middle of each side: http://en.wikipedia.org/wiki/Koch_snowflake#Properties

We already had a kolmogrov-complexity Koch Snowflake challenge for n=4. The new challenge is to draw a Koch snowflake with any n between 1 and 10.

Rules
The snowflakes may not be hardcoded in the program or in files - they must be generated by your program.

Your program must support all sized n between 1 and 10.

The number of sides must be input by the user through std-in.

You must print a graphical representation of the snowflake to the screen.

Sample Koch Snowflakes with n equaling 1, 2, 3, and 4 (green lines for clarity only, do not reproduce them):

https://i.sstatic.net/5RWxr.png

https://codegolf.stackexchange.com/questions/41011/graphical-representation-of-koch-snowflake

"""

from turtle import *
import sys

def recurse(l, d):
    for x in [1, -2, 1, 0]:
        if d > 0:
            recurse(l, d - 1)
            rt(60*x)
        else:
            fd(l)

def snowflake(n):
    for i in 'lol':
        lt(120)
        recurse(3, n)

def main():
    if len(sys.argv) != 2:
        print("usage: <n>")
        exit(2)

    snowflake(int(sys.argv[1]))
    exitonclick()

main()
