/*

FizzBuzz is so simple, bet you can do it backwards. In this challenge, you will be given the length of the FizzBuzz string and must give the positive integer that produced that string.

Description
To break this down, a FizzBuzz string for n is generated by the following algorithm.

Start with an empty string and, for every i=1..n (inclusive):

If i is divisible by 3 and by 5, append FizzBuzz to the string.
If i is just divisible by 3 append Fizz.
If i is just divisible by 5 append Buzz.
If i is divisible by neither, append the decimal representation of i.
So for example FizzBuzz(15) is the following:

12Fizz4BuzzFizz78FizzBuzz11Fizz1314FizzBuzz
You will be given Length(FizzBuzz(n)) and must determine n. You may assume that the input is positive and is always going to be the length of some FizzBuzz string.

Rules
Your solution may a complete program or a function definition in any standardly acceptable language. Your program/function may take in arguments and return answers in any standardly accepted way. Standard loopholes are forbidden.

You may assume that the input is positive and valid (describes the length of some FizzBuzz string) and is smaller than the largest integer representable natively in your language.

This is code golf, so shortest byte-count wins.

Examples
Here are some example cases

Length(FizzBuzz(n)) -> n
1                   -> 1
6                   -> 3
15                  -> 6
313                 -> 100
3677                -> 1001
Edit
Fixed last test case. Thanks @SteadyBox.

*/

#include <assert.h>
#include <stdio.h>

int
f(int n)
{
	int i, l;

	i = l = 0;
	while (l < n) {
		i += 1;
		if (i % 3) {
			if (i % 5)
				l += snprintf(NULL, 0, "%d", i);
			else
				l += 4;
		} else {
			if (i % 5)
				l += 4;
			else
				l += 8;
		}
	}
	return i;
}

int
main()
{
	assert(f(1) == 1);
	assert(f(6) == 3);
	assert(f(15) == 6);
	assert(f(313) == 100);
	assert(f(3677) == 1001);

	return 0;
}
