#!/usr/bin/env python3

"""

Description
"Imtiaz Germain primes" is not a technical name in Mathematics, but my weird creation, in the memoir of the famous mathematician Sophie Germain. These primes can be generated by the following process:

1. Take a Safe prime
2. Apply 2p + 1 on it to obtain a composite number
3. Apply 2p + 1 once more to obtain a prime number
The idea can be further illustrated in the example.

Example
We check if 3 is a Sophie Germain prime. It has a safe prime 7 using 2p+1 so 3 is a Sophie Germain prime and can/cannot be an Imtiaz Germain prime. We take the safe prime, apply 2p+1 on it, and get 15 which must be composite according to the second step of the description, applying the same, we must get a prime next, which is 31 so 3 is an Imtiaz Germain prime. All Imtiaz Germain primes below 100M are available in Chapter 1 of the book I wrote here.

Task
Write a program, which inputs any number, and mentions all Imtiaz Germain primes below the number. As long as fulfills the full output, you may output the Imtiaz Germain primes in reversed order. Since it is code golf, the shortest code in bytes win, if bytes are equated then the earliest posted program wins.

Test Cases
10 => 3
1500 => 3 23 29 53 113 233 293 419 593 653 659 683 1013 1103 1223 1439
10000 => 3 23 29 53 113 233 293 419 593 653 659 683 1013 1103 1223 1439 1559 1583 1973 2039 2273 2339 2549 2753 3299 3359 3593 3803 3863 4019 4409 4733 4793 4919 4943 5003 5279 5639 6173 6263 6269 6323 6563 6983 7433 7643 7823 8243 8273 8513

"""

from sympy import isprime

"""

@lyxal

If I've understood the challenge correctly, for a number to be Imtiaz Germain,
it has to first be prime, and applying 2p+1 3 times must produce the required pattern.
Hence, the list [p, 2p + 1, 2(2p + 1) + 1, 2((2(2p + 1) + 1) + 1)] must equal [1, 1, 0, 1].

"""
def isigp(n):
    p = n
    for i in [1, 1, 0, 1]:
        if isprime(p) != i:
            return False
        p = 2*p + 1
    return True

def upto(n):
    r = []
    for i in range(1, n + 1):
        if isigp(i):
            r.append(i)
    return r

def main():
    assert(upto(10) == [3])
    assert(upto(1500) == [3, 23, 29, 53, 113, 233, 293, 419, 593, 653, 659, 683, 1013, 1103, 1223, 1439])
    assert(upto(10000) == [3, 23, 29, 53, 113, 233, 293, 419, 593, 653, 659, 683, 1013, 1103, 1223, 1439, 1559, 1583, 1973, 2039, 2273, 2339, 2549, 2753, 3299, 3359, 3593, 3803, 3863, 4019, 4409, 4733, 4793, 4919, 4943, 5003, 5279, 5639, 6173, 6263, 6269, 6323, 6563, 6983, 7433, 7643, 7823, 8243, 8273, 8513])

main()
