#!/usr/bin/env python3

"""

Suppose you're given some distinct uppercase letters scattered in a rectangular array of otherwise-blank cells. Each cell in the array belongs to the letter nearest to it, defined as the letter reachable in the smallest number of horizontal and/or vertical steps -- no diagonal steps. (If a cell is equidistant from two or more nearest letters, it belongs to whichever of those letters is first in alphabetical order. A cell with an uppercase letter in it belongs to that letter.) Boundary-cells are those that are horizontally or vertically adjacent to one or more cells that do not belong to the letter that they themselves belong to.

Write a procedure subprogram with the following behavior, producing a kind of Voronoi diagram ...

Input: Any ASCII string composed only of dots, uppercase letters, and newlines, such that when printed it displays a rectangular array of the kind described above, with dots acting as blanks.

Output: A printout of the input string with each blank boundary-cell replaced by the lowercase version of the letter it belongs to. (The subprogram does the printing.)

Example 1

Input:

......B..
.........
...A.....
.........
.......D.
.........
.C.......
.....E...
.........
Output:

...ab.B..
....ab.bb
...A.abdd
aa...ad..
cca.ad.D.
..caeed..
.C.ce.edd
..ce.E.ee
..ce.....

A sketch highlighting the boundaries:
https://i.sstatic.net/1XwIQ.gif

Example 2

Input:

............................U...........
......T.................................
........................................
.....................G..................
..R.......S..........F.D.E............I.
.........................H..............
.....YW.Z...............................
......X.................................
........................................
........................................
......MN...........V....................
......PQ................................
........................................
.............L...............J..........
........................................
........................................
....C...........K.......................
........................................
..................................A.....
...........B............................
Output:

..rt.....ts...sg......gduu..U.....ui....
..rt..T..ts...sg......gddeu......ui.....
...rt...ts....sg......gddeeu....ui......
....rttts.....sggggggGgdde.euuuui.......
..R.rywss.S....sfffffFdDdEeeeeeei.....I.
...ryywwzs.....sf....fddhHhhhhhhhi......
..ryyYWwZzs..sssffff.fddh.......hi......
..rxxxXxzzs.sllvvvvvffddh....hhhhi......
rrrxxxxnzzssl.lv....vfddh...hjjjjii.....
mmmmmmmnnnnnl.lv.....vvdh..hj....jai....
mmmmmmMNnnnnl.lv...V...vvhhj.....jaai...
ppppppPQqqql...lv.......vhj......ja.ai..
ppppp.pq.ql....lkv.....vjj.......ja..aii
cccccppqql...L.lkkv...vj.....J...ja...aa
.....cpqqlll..lk..kvvvvj........ja......
......cccbbbllk....kkkkj.......ja.......
....C...cb..bk..K......kj.....ja........
.......cb....bk........kjjjjjja.........
......cb......bk.......kaaaaaa....A.....
.....cb....B...bk......ka...............

Color enhancement:
https://i.sstatic.net/IuKCW.gif
"""

"""

Ported from @Keith Randall solution

Does a flood fill to compute the result.
The trailing for/zip combo generates an array x for each cell containing the value in that cell and its four neighbors.
Then we use Blckknght's trick and min a bunch of possibilities for each cell.
Those are the original cell value, any neighbors if the cell has not been visited yet, or a .
if it has been visited and all neighbors are . or equal to the cell itself.

"""
def voronoi_diagram(text):
    width = text.index("\n") + 1
    text = text.replace(".", "~")

    for _ in range(2 * width):
        windows = zip(
            text,
            text[1:] + "\n",
            text[width:] + "\n" * width,
            "\n" + text,
            "\n" * width + text,
        )

        output = []
        for window in windows:
            first = window[0]
            candidates = [first]
            if first == "~":
                for char in window:
                    if char > "\n":
                        candidates.append(char.lower())
            else:
                valid = True
                for char in window:
                    if char.lower() not in (".\n" + first):
                        valid = False
                        break
                if valid:
                    candidates.append(".")
            
            output.append(min(candidates))
        
        text = "".join(output)
    
    print(text)

voronoi_diagram("""......B..
.........
...A.....
.........
.......D.
.........
.C.......
.....E...
.........
""")

voronoi_diagram("""............................U...........
......T.................................
........................................
.....................G..................
..R.......S..........F.D.E............I.
.........................H..............
.....YW.Z...............................
......X.................................
........................................
........................................
......MN...........V....................
......PQ................................
........................................
.............L...............J..........
........................................
........................................
....C...........K.......................
........................................
..................................A.....
...........B............................""")
