#!/bin/sh

cat << EOF >/dev/null

Given a list of countries in alphabetical order, put them in the same order as they are given in the song "Yakko's World".

Specifically, you are given the following list of countries* exactly:

Abu Dhabi, Afghanistan, Albania, Algeria, Algiers, Angola, Argentina, Australia, Austria, Bahamas, Bahrain, Bangladesh, Barbados, Belgium, Belize, Benin, Bermuda, Bhutan, Bolivia, Borneo, Botswana, Brazil, Bulgaria, Burma, Burundi, Cameroon, Canada, Caribbean, Cayman, Chad, Chile, China, Colombia, Congo, Costa Rica, Crete, Cuba, Cyprus, Czechoslovakia, Dahomey, Denmark, Djibouti, Ecuador, Egypt, El Salvador, England, Ethiopia, Fiji, Finland, France, French Guiana, Gabon, Gambia, Germany, Ghana, Greece, Greenland, Guam, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Honduras, Hong Kong, Hungary, Iceland, India, Indonesia, Iran, Iraq, Ireland, Israel, Italy, Jamaica, Japan, Jordan, Kampuchea, Kenya, Korea, Kuwait, Laos, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Luxembourg, Madagascar, Mahore, Malawi, Malaysia, Mali, Malta, Mauritania, Mexico, Monaco, Mongolia, Morocco, Mozambique, Namibia, Nepal, New Guinea, New Zealand, Nicaragua, Niger, Nigeria, Norway, Oman, Pakistan, Palestine, Panama, Paraguay, Peru, Poland, Portugal, Puerto Rico, Qatar, Republic Dominican, Romania, Russia, Rwanda, San Juan, Saudi Arabia, Scotland, Senegal, Sierra Leone, Somalia, Spain, Sri Lanka, Sudan, Sumatra, Surinam, Swaziland, Sweden, Switzerland, Syria, Taiwan, Tanzania, Thailand, The Netherlands, The Philippine Islands, Tibet, Tobago, Togo, Transylvania, Tunisia, Turkey, Uganda, United States, Uruguay, Venezuela, Vietnam, Yemen, Yugoslavia, Zaire, Zambia, Zimbabwe
And required to output the countries in this order:

United States, Canada, Mexico, Panama, Haiti, Jamaica, Peru, Republic Dominican, Cuba, Caribbean, Greenland, El Salvador, Puerto Rico, Colombia, Venezuela, Honduras, Guyana, Guatemala, Bolivia, Argentina, Ecuador, Chile, Brazil, Costa Rica, Belize, Nicaragua, Bermuda, Bahamas, Tobago, San Juan, Paraguay, Uruguay, Surinam, French Guiana, Barbados, Guam, Norway, Sweden, Iceland, Finland, Germany, Switzerland, Austria, Czechoslovakia, Italy, Turkey, Greece, Poland, Romania, Scotland, Albania, Ireland, Russia, Oman, Bulgaria, Saudi Arabia, Hungary, Cyprus, Iraq, Iran, Syria, Lebanon, Israel, Jordan, Yemen, Kuwait, Bahrain, The Netherlands, Luxembourg, Belgium, Portugal, France, England, Denmark, Spain, India, Pakistan, Burma, Afghanistan, Thailand, Nepal, Bhutan, Kampuchea, Malaysia, Bangladesh, China, Korea, Japan, Mongolia, Laos, Tibet, Indonesia, The Philippine Islands, Taiwan, Sri Lanka, New Guinea, Sumatra, New Zealand, Borneo, Vietnam, Tunisia, Morocco, Uganda, Angola, Zimbabwe, Djibouti, Botswana, Mozambique, Zambia, Swaziland, Gambia, Guinea, Algeria, Ghana, Burundi, Lesotho, Malawi, Togo, Niger, Nigeria, Chad, Liberia, Egypt, Benin, Gabon, Tanzania, Somalia, Kenya, Mali, Sierra Leone, Algiers, Dahomey, Namibia, Senegal, Libya, Cameroon, Congo, Zaire, Ethiopia, Guinea-Bissau, Madagascar, Rwanda, Mahore, Cayman, Hong Kong, Abu Dhabi, Qatar, Yugoslavia, Crete, Mauritania, Transylvania, Monaco, Liechtenstein, Malta, Palestine, Fiji, Australia, Sudan
You have some flexibility in the form of the input and output; you can take or output the countries as all uppercase, all lowercase, or maintaining case, and can choose to omit spaces as well.

Standard loopholes are forbidden. Since this is code-golf, the shortest code wins.

*Note that Yakko's World includes several places that aren't countries, and that several countries aren't included in the list.

EOF

echo "United States, Canada, Mexico, Panama, Haiti, Jamaica, Peru, Republic Dominican, Cuba, Caribbean, Greenland, El Salvador, Puerto Rico, Colombia, Venezuela, Honduras, Guyana, Guatemala, Bolivia, Argentina, Ecuador, Chile, Brazil, Costa Rica, Belize, Nicaragua, Bermuda, Bahamas, Tobago, San Juan, Paraguay, Uruguay, Surinam, French Guiana, Barbados, Guam, Norway, Sweden, Iceland, Finland, Germany, Switzerland, Austria, Czechoslovakia, Italy, Turkey, Greece, Poland, Romania, Scotland, Albania, Ireland, Russia, Oman, Bulgaria, Saudi Arabia, Hungary, Cyprus, Iraq, Iran, Syria, Lebanon, Israel, Jordan, Yemen, Kuwait, Bahrain, The Netherlands, Luxembourg, Belgium, Portugal, France, England, Denmark, Spain, India, Pakistan, Burma, Afghanistan, Thailand, Nepal, Bhutan, Kampuchea, Malaysia, Bangladesh, China, Korea, Japan, Mongolia, Laos, Tibet, Indonesia, The Philippine Islands, Taiwan, Sri Lanka, New Guinea, Sumatra, New Zealand, Borneo, Vietnam, Tunisia, Morocco, Uganda, Angola, Zimbabwe, Djibouti, Botswana, Mozambique, Zambia, Swaziland, Gambia, Guinea, Algeria, Ghana, Burundi, Lesotho, Malawi, Togo, Niger, Nigeria, Chad, Liberia, Egypt, Benin, Gabon, Tanzania, Somalia, Kenya, Mali, Sierra Leone, Algiers, Dahomey, Namibia, Senegal, Libya, Cameroon, Congo, Zaire, Ethiopia, Guinea-Bissau, Madagascar, Rwanda, Mahore, Cayman, Hong Kong, Abu Dhabi, Qatar, Yugoslavia, Crete, Mauritania, Transylvania, Monaco, Liechtenstein, Malta, Palestine, Fiji, Australia, Sudan"
